#!/usr/bin/env python

import sys, os, re

# Collect the parameters
commit_msg_filepath = sys.argv[1]

REGEX = r"(feat|fix|refactor|perf|style|test|docs|build|ops)(?:\([\w\s]+\))*: [\w .]+"

def raise_error(msg):
    print(msg)
    raise Exception(msg)


with open(commit_msg_filepath, 'r+') as f:
  commit = f.read()
  match = re.search(REGEX, commit)
  if match == None:
    raise_error("Commit doesn't match the pattern...")
